# fix data preprocess reduce mel bin size.
# increase max_frame: 512 -> 1024
# num_mels: 128 -> 64
###########################################################
#                      GLOBAL SETTING                     #
###########################################################
seed: 1
n_class: 25
n_fold: 5
###########################################################
#                    PREPROCESS SETTING                   #
###########################################################
sr: 48000
fft_size: 2048
hop_size: 512
window: hann
num_mels: 64
fmin: 50
fmax: 16000
###########################################################
#                     NETWORK SETTING                     #
###########################################################
model_type: "Cnn14_DecisionLevelAtt" # pretrained model's type.
att_block:
  n_in: 2048
  n_out: 25
  activation: linear

model_params:
  sample_rate: 16000
  window_size: 1024
  hop_size: 256
  mel_bins: 64
  fmin: 50
  fmax: 8000
  classes_num: 527
  require_prep: False
  is_spec_augmenter: True
###########################################################
#                    TRAINING SETTING                     #
###########################################################
# dataset
train_dataset_mode: tp
allow_cache: True # Whether to allow cache in dataset. If true, it requires cpu memory.
is_normalize: False
# collater_fc
max_frames: 1024
l_target: 32
collater_mode: sum
# dataloader
accum_grads: 2
batch_size: 32 # Batch size.
pin_memory: False # Whether to pin memory in Pytorch DataLoader.
num_workers: 2 # Number of workers in Pytorch DataLoader.
# trainer
use_center_loss: False
###########################################################
#                       LOSS SETTING                      #
###########################################################
loss_type: FrameClipLoss
loss_params:
  clip_ratio: 0.5
  reduction: mean

###########################################################
#              OPTIMIZER & SCHEDULER SETTING              #
###########################################################
optimizer_type: "Adam"
optimizer_params:
  conv_lr: 0.0001 # convolution layer's learning rate.
  fc_lr: 0.001 # full connection layer's learning rate.
scheduler_type: "CosineAnnealingLR"
scheduler_params:
  T_max: 500 # scheduler step size.
  eta_min: 1.0e-6
###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 3000 # Number of training steps.
save_interval_steps: 1000 # Interval steps to save checkpoint.
eval_interval_epochs: 5 # Interval epochs to evaluate the network.
###########################################################
#                     OTHER SETTING                       #
###########################################################
n_eval_split: 20
