# intrepolate shumamura0 stgategy by efficent net b0, update lr=0.001, fix collater_fc and model(sa same as v010)
# PANNs SED architecture
# ClipFrame Loss
# Random 10sec clip
# Using only tp file
# MixUp
# The base model is EfficientNet_simple
###########################################################
#                      GLOBAL SETTING                     #
###########################################################
seed: 1
n_class: 24
n_fold: 5
###########################################################
#                    PREPROCESS SETTING                   #
###########################################################
sr: 48000
fft_size: 2048
hop_size: 512
window: hann
num_mels: 128
fmin: 50
fmax: 16000
###########################################################
#                     NETWORK SETTING                     #
###########################################################
model_type: "EfficientNet_b"
model_params:
  classes_num: 24
  efficient_net_name: efficientnet-b0
  feat_dim: 1280
  is_spec_augmenter: false
  use_dializer: true
###########################################################
#                    TRAINING SETTING                     #
###########################################################
# augmentation
wave_mode: true
mixup_alpha: 0.2
augmentation_params:
  PinkNoiseSNR: { always_apply: False, p: 0.5, min_snr: 5.0, max_snr: 40.0 }
  GaussianNoiseSNR: { always_apply: False, p: 0.5, min_snr: 5.0, max_snr: 40.0 }
  VolumeControl: { always_apply: False, p: 0.5, db_limit: 10, mode: cosine }

# dataset
train_dataset_mode: tp
allow_cache: false # Whether to allow cache in dataset. If true, it requires cpu memory.
is_normalize: false
use_on_the_fly: true
# collater_fc
max_frames: 938
l_target: 30
collater_mode: binary
random: false
# dataloader
accum_grads: 2
batch_size: 32 # Batch size.
pin_memory: false # Whether to pin memory in Pytorch DataLoader.
num_workers: 2 # Number of workers in Pytorch DataLoader.
# trainer
use_center_loss: false
use_dializer: false
###########################################################
#                       LOSS SETTING                      #
###########################################################
loss_type: BCEWithLogitsLoss
loss_params:
  reduction: mean

###########################################################
#              OPTIMIZER & SCHEDULER SETTING              #
###########################################################
optimizer_type: "Adam"
optimizer_params:
  lr: 0.0008
scheduler_type: "StepLR"
scheduler_params:
  step_size: 1000 # scheduler step size.
  gamma: 0.5
###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 3000 # Number of training steps.
save_interval_steps: 3000 # Interval steps to save checkpoint.
eval_interval_epochs: 5 # Interval epochs to evaluate the network.
###########################################################
#                     OTHER SETTING                       #
###########################################################
sec: 10
n_eval_split: 7
