# intrepolate shumamura0 stgategy by efficent net b0, update lr=0.001, fix collater_fc and model(balanced)
# PANNs SED architecture
# BCEWithLogitsLoss + Dializerloss + center
# Random 10sec clip
# Using only tp file
# MixUp
# The base model is EfficientNet_b
###########################################################
#                      GLOBAL SETTING                     #
###########################################################
seed: 1
n_class: 26
n_fold: 5
###########################################################
#                    PREPROCESS SETTING                   #
###########################################################
sr: 48000
fft_size: 2048
hop_size: 512
window: hann
num_mels: 128
fmin: 0
fmax: 16000
###########################################################
#                     NETWORK SETTING                     #
###########################################################
model_type: "EfficientNet_b"
model_params:
  classes_num: 26
  efficient_net_name: efficientnet-b0
  feat_dim: 1280
  is_spec_augmenter: false
  use_dializer: true
###########################################################
#                    TRAINING SETTING                     #
###########################################################
# augmentation
mixup_alpha: 0.1
# dataset
train_dataset_mode: tp
allow_cache: true # Whether to allow cache in dataset. If true, it requires cpu memory.
is_normalize: false
# batch sampler
# batch_sampler_type: MultiLabelBalancedBatchSampler
# collater_fc
max_frames: 1024
l_target: 32
collater_mode: binary
use_song_type: true
random: false
# dataloader
accum_grads: 2
batch_size: 32 # Batch size.
pin_memory: true # Whether to pin memory in Pytorch DataLoader.
num_workers: 2 # Number of workers in Pytorch DataLoader.
# trainer
use_center_loss: true
use_dializer: true
###########################################################
#                       LOSS SETTING                      #
###########################################################
loss_type: BCEWithLogitsLoss
loss_params:
  reduction: mean
  pos_weight: [24.32, 24.32, 32.86486486486486, 24.32, 24.32, 24.32, 24.32, 24.32, 24.32, 35.76470588235294, 24.32, 24.32, 24.32, 24.32, 24.32, 24.32, 24.32, 30.4, 24.32, 28.27906976744186, 30.4, 24.32, 27.636363636363637, 24.32, 43.42857142857143, 24.32]

dializer_loss_alpha: 0.5
dializer_loss_type: BCEWithLogitsLoss
dializer_loss_params:
  reduction: mean

center_loss_alpha: 5.0e-5
center_loss_params:
  num_classes: 24
  feat_dim: 1280

tsne_params:
  n_components: 2
  random_state: 0
  perplexity: 30
  n_iter: 1000
###########################################################
#              OPTIMIZER & SCHEDULER SETTING              #
###########################################################
optimizer_type: Noam
optimizer_params:
  base_lr: 0.1
  model_size: 128
  warmup: 3000
  betas: [0.9, 0.999]

center_optimizer_type: Adam
center_loss_optimizer_params:
  lr: 0.0001
  weight_decay: 1.0e-4

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 3000 # Number of training steps.
save_interval_steps: 3000 # Interval steps to save checkpoint.
eval_interval_epochs: 5 # Interval epochs to evaluate the network.
###########################################################
#                     OTHER SETTING                       #
###########################################################
n_eval_split: 7
additional_steps: 1000
