# intrepolate shumamura0 stgategy by efficent net b0, update lr=0.001, fix collater_fc and model(sa same as v023)
# PANNs SED architecture
# BCEWithLogitsLoss + Dializerloss + center
# Random 10sec clip
# Using only tp file
# MixUp
# The base model is EfficientNet_b
###########################################################
#                      GLOBAL SETTING                     #
###########################################################
seed: 1
n_class: 24
n_fold: 5
###########################################################
#                    PREPROCESS SETTING                   #
###########################################################
sr: 48000
fft_size: 2048
hop_size: 512
window: hann
num_mels: 128
fmin: 50
fmax: 16000
###########################################################
#                     NETWORK SETTING                     #
###########################################################
model_type: "ResNext50" # pretrained model's type.
att_block:
  n_in: 2048
  n_out: 24
  activation: linear

model_params:
  num_mels: 128
  classes_num: 24
  require_prep: false
  is_spec_augmenter: false
  use_dializer: true
###########################################################
#                    TRAINING SETTING                     #
###########################################################
# augmentation
mixup_alpha: 0.1
# dataset
train_dataset_mode: tp
allow_cache: true # Whether to allow cache in dataset. If true, it requires cpu memory.
is_normalize: false
# collater_fc
max_frames: 1024
l_target: 32
collater_mode: binary
random: false
# dataloader
accum_grads: 4
batch_size: 32 # Batch size.
pin_memory: false # Whether to pin memory in Pytorch DataLoader.
num_workers: 2 # Number of workers in Pytorch DataLoader.
# trainer
use_center_loss: true
use_dializer: true
###########################################################
#                       LOSS SETTING                      #
###########################################################
loss_type: BCEWithLogitsLoss
loss_params:
  reduction: mean

dializer_loss_alpha: 0.5
dializer_loss_type: BCEWithLogitsLoss
dializer_loss_params:
  reduction: mean

center_loss_alpha: 5.0e-5
center_loss_params:
  num_classes: 24
  feat_dim: 2048

tsne_params:
  n_components: 2
  random_state: 0
  perplexity: 30
  n_iter: 1000
###########################################################
#              OPTIMIZER & SCHEDULER SETTING              #
###########################################################
optimizer_type: "Adam"
optimizer_params:
  conv_lr: 0.001 # convolution layer's learning rate.
  fc_lr: 0.001 # full connection layer's learning rate.
center_loss_optimizer_params:
  lr: 0.0001
scheduler_type: "StepLR"
scheduler_params:
  step_size: 1000 # scheduler step size.
  gamma: 0.5
###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 6000 # Number of training steps.
save_interval_steps: 3000 # Interval steps to save checkpoint.
eval_interval_epochs: 5 # Interval epochs to evaluate the network.
###########################################################
#                     OTHER SETTING                       #
###########################################################
n_eval_split: 7
