# intrepolate shumamura0 stgategy by efficent net b0, update lr=0.001, fix collater_fc and model(sa same as v010)
# PANNs SED architecture
# ClipFrame Loss
# Random 10sec clip
# Using only tp file
# MixUp
# The base model is EfficientNet_simple
###########################################################
#                      GLOBAL SETTING                     #
###########################################################
seed: 1
n_class: 24
n_fold: 5
###########################################################
#                    PREPROCESS SETTING                   #
###########################################################
sr: 48000
fft_size: 2048
hop_size: 512
window: hann
num_mels: 128
fmin: 50
fmax: 16000
###########################################################
#                     NETWORK SETTING                     #
###########################################################
model_type: "TransformerEncoderDecoder"
model_params:
  num_features: 128
  num_classes: 24
  sequence_length: 1024
  num_blocks: 4
  num_hidden_units: 128
  num_feedforward_units: 256
  num_heads: 4
  num_latent_units: 32
  dropout: 0.2
  use_position_encode: false
  use_reconstruct: false
  use_dializer: true
  is_spec_augmenter: false
###########################################################
#                    TRAINING SETTING                     #
###########################################################
# augmentation
mixup_alpha: 0.1
# dataset
train_dataset_mode: tp
allow_cache: true # Whether to allow cache in dataset. If true, it requires cpu memory.
is_normalize: false
# collater_fc
max_frames: 1024
l_target: 1024
collater_mode: binary
random: false
# dataloader
accum_grads: 32
batch_size: 16 # Batch size.
pin_memory: false # Whether to pin memory in Pytorch DataLoader.
num_workers: 4 # Number of workers in Pytorch DataLoader.
# trainer
use_center_loss: false
use_dializer: true
###########################################################
#                       LOSS SETTING                      #
###########################################################
loss_type: BCEWithLogitsLoss
loss_params:
  reduction: mean

dializer_loss_alpha: 0.5
dializer_loss_type: BCEWithLogitsLoss
dializer_loss_params:
  reduction: mean
###########################################################
#              OPTIMIZER & SCHEDULER SETTING              #
###########################################################
optimizer_type: Noam
optimizer_params:
  base_lr: 0.1
  model_size: 128
  warmup: 8000
  betas: [0.9, 0.999]

scheduler_type: null
###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 10000 # Number of training steps.
save_interval_steps: 5000 # Interval steps to save checkpoint.
eval_interval_epochs: 5 # Interval epochs to evaluate the network.
###########################################################
#                     OTHER SETTING                       #
###########################################################
n_eval_split: 7
